
export function GreekCharacters( editor ) {
	editor.plugins.get( 'SpecialCharacters' ).addItems( 'Greek', [
		{ title: 'Greek small letter a', character: 'α' },
		{ title: 'Greek small letter b', character: 'β' },
		{ title: 'Greek small letter c', character: 'γ' },
		{ title: 'Greek small letter d', character: 'δ' },
		{ title: 'Greek small letter e', character: 'ε' },
		{ title: 'Greek small letter f', character: 'ζ' },
		{ title: 'Greek small letter g', character: 'η' },
		{ title: 'Greek small letter h', character: 'θ' },
		{ title: 'Greek small letter i', character: 'ι' },
		{ title: 'Greek small letter j', character: 'κ' },
		{ title: 'Greek small letter k', character: 'λ' },
		{ title: 'Greek small letter l', character: 'μ' },
		{ title: 'Greek small letter m', character: 'ν' },
		{ title: 'Greek small letter n', character: 'ξ' },
		{ title: 'Greek small letter o', character: 'ο' },
		{ title: 'Greek small letter p', character: 'π' },
		{ title: 'Greek small letter q', character: 'ρ' },
		{ title: 'Greek small letter r', character: 'ς' },
		{ title: 'Greek small letter s', character: 'σ' },
		{ title: 'Greek small letter t', character: 'τ' },
		{ title: 'Greek small letter u', character: 'υ' },
		{ title: 'Greek small letter v', character: 'φ' },
		{ title: 'Greek small letter w', character: 'χ' },
		{ title: 'Greek small letter x', character: 'ψ' },
		{ title: 'Greek small letter y', character: 'ω' },
		{ title: 'Greek capital letter A', character: 'Α' },
		{ title: 'Greek capital letter B', character: 'Β' },
		{ title: 'Greek capital letter C', character: 'Γ' },
		{ title: 'Greek capital letter D', character: 'Δ' },
		{ title: 'Greek capital letter E', character: 'Ε' },
		{ title: 'Greek capital letter F', character: 'Ζ' },
		{ title: 'Greek capital letter G', character: 'Η' },
		{ title: 'Greek capital letter H', character: 'Θ' },
		{ title: 'Greek capital letter I', character: 'Ι' },
		{ title: 'Greek capital letter J', character: 'Κ' },
		{ title: 'Greek capital letter K', character: 'Λ' },
		{ title: 'Greek capital letter L', character: 'Μ' },
		{ title: 'Greek capital letter M', character: 'Ν' },
		{ title: 'Greek capital letter N', character: 'Ξ' },
		{ title: 'Greek capital letter O', character: 'Ο' },
		{ title: 'Greek capital letter P', character: 'Π' },
		{ title: 'Greek capital letter Q', character: 'Ρ' },
		{ title: 'Greek capital letter R', character: 'Σ' },
		{ title: 'Greek capital letter S', character: 'Σ' },
		{ title: 'Greek capital letter T', character: 'Τ' },
		{ title: 'Greek capital letter U', character: 'Υ' },
		{ title: 'Greek capital letter V', character: 'Φ' },
		{ title: 'Greek capital letter W', character: 'Χ' },
		{ title: 'Greek capital letter X', character: 'Ψ' },
		{ title: 'Greek capital letter Y', character: 'Ω' }
	] );
}
