
export function GreekCharacters( editor ) {
	editor.plugins.get( 'SpecialCharacters' ).addItems( 'Greek', [
		{ title: 'Greek small letter Alpha', character: 'α' },
		{ title: 'Greek small letter Beta', character: 'β' },
		{ title: 'Greek small letter Gamma', character: 'γ' },
		{ title: 'Greek small letter Delta', character: 'δ' },
		{ title: 'Greek small letter Epsilion', character: 'ε' },
		{ title: 'Greek small letter Zeta', character: 'ζ' },
		{ title: 'Greek small letter Eta', character: 'η' },
		{ title: 'Greek small letter Theta', character: 'θ' },
		{ title: 'Greek small letter Iota', character: 'ι' },
		{ title: 'Greek small letter Kappa', character: 'κ' },
		{ title: 'Greek small letter Lambda', character: 'λ' },
		{ title: 'Greek small letter Mu', character: 'μ' },
		{ title: 'Greek small letter Nu', character: 'ν' },
		{ title: 'Greek small letter Xi', character: 'ξ' },
		{ title: 'Greek small letter Omicron', character: 'ο' },
		{ title: 'Greek small letter Pi', character: 'π' },
		{ title: 'Greek small letter Rho', character: 'ρ' },
		{ title: 'Greek small letter Sigma', character: 'ς' },
		{ title: 'Greek small letter Sigma', character: 'σ' },
		{ title: 'Greek small letter Tau', character: 'τ' },
		{ title: 'Greek small letter Upsilon', character: 'υ' },
		{ title: 'Greek small letter Phi', character: 'φ' },
		{ title: 'Greek small letter Chi', character: 'χ' },
		{ title: 'Greek small letter Psi', character: 'ψ' },
		{ title: 'Greek small letter Omega', character: 'ω' },
		{ title: 'Greek capital letter Alpha', character: 'Α' },
		{ title: 'Greek capital letter Beta', character: 'Β' },
		{ title: 'Greek capital letter Gamma', character: 'Γ' },
		{ title: 'Greek capital letter Delta', character: 'Δ' },
		{ title: 'Greek capital letter Epsilion', character: 'Ε' },
		{ title: 'Greek capital letter Zeta', character: 'Ζ' },
		{ title: 'Greek capital letter Eta', character: 'Η' },
		{ title: 'Greek capital letter Theta', character: 'Θ' },
		{ title: 'Greek capital letter Iota', character: 'Ι' },
		{ title: 'Greek capital letter Kappa', character: 'Κ' },
		{ title: 'Greek capital letter Lambda', character: 'Λ' },
		{ title: 'Greek capital letter Mu', character: 'Μ' },
		{ title: 'Greek capital letter Nu', character: 'Ν' },
		{ title: 'Greek capital letter Xi', character: 'Ξ' },
		{ title: 'Greek capital letter Omicron', character: 'Ο' },
		{ title: 'Greek capital letter Pi', character: 'Π' },
		{ title: 'Greek capital letter Rho', character: 'Ρ' },
		{ title: 'Greek capital letter Sigma', character: 'Σ' },
		{ title: 'Greek capital letter Tau', character: 'Τ' },
		{ title: 'Greek capital letter Upsilon', character: 'Υ' },
		{ title: 'Greek capital letter Phi', character: 'Φ' },
		{ title: 'Greek capital letter Chi', character: 'Χ' },
		{ title: 'Greek capital letter Psi', character: 'Ψ' },
		{ title: 'Greek capital letter Omega', character: 'Ω' }
	] );
}
